# 写在前面

源订单信息 -> 筛选出第一医院的订单 -> 统一医院名称字段 -> 删除无对应护工的订单记录 -> 修改、删除患者年龄不合法的订单记录 | 订单信息（清洗后）.csv

-> 规范病区与床位号字段 -> 订单号科学计数法转字符串 -> 费用相关字段单位由分转元 -> 部分字段名称语义增强 | 订单信息.csv

-> 不考虑床位号为空的订单记录 | 订单信息（不考虑床位号为空）.csv

护工信息.csv：订单数、活跃度在订单信息.csv的基础上计算得到

护工信息（不考虑床位号为空）.csv：订单数、活跃度在订单信息（不考虑床位号为空）.csv的基础上计算得到

In [5]:
with open('dataMyself/患者_订单.txt', 'r') as file:
    res = []
    for line in file.readlines():
        line = line.replace('\n', '')
        arr = eval(line.split('->')[1])
        for item in arr:
            if item not in res:
                res.append(item)
    print(res)
    print(len(res))

[0, 82, 85, 173, 175, 649, 233, 240, 1286, 317, 712, 726, 759, 958, 1219, 2291, 1, 52, 68, 86, 100, 130, 131, 135, 479, 564, 634, 641, 968, 1042, 2095, 2153, 2, 6, 77, 176, 83, 143, 142, 160, 179, 199, 203, 212, 213, 279, 577, 1669, 753, 1981, 2248, 3, 36, 57, 58, 170, 61, 62, 66, 94, 92, 1092, 1113, 1382, 2301, 7, 17, 53, 1069, 1582, 21, 28, 29, 678, 30, 1132, 47, 197, 110, 165, 178, 204, 1860, 206, 1220, 1821, 2267, 249, 585, 589, 709, 839, 1275, 1692, 2057, 19, 104, 168, 224, 311, 554, 664, 723, 877, 965, 997, 1088, 1321, 1579, 1119, 1133, 1258, 1292, 1461, 1619, 1505, 1580, 1685, 1733, 1772, 1958, 1927, 2304, 2383, 1944, 1946, 2066, 2497, 2538, 20, 1309, 91, 1279, 1618, 1721, 97, 1949, 105, 362, 1563, 202, 1483, 1858, 1952, 214, 230, 273, 395, 2011, 458, 1197, 504, 1057, 1734, 667, 711, 793, 1206, 1402, 1414, 1532, 1437, 1588, 2049, 1599, 1647, 2376, 1787, 2106, 1803, 2550, 1874, 1926, 35, 728, 177, 180, 190, 196, 201, 248, 467, 802, 1738, 1818, 2278, 2551, 37, 413, 1531, 38, 725, 64, 67, 329, 112, 223, 1802, 238, 251, 252, 435, 521, 253, 270, 275, 1374, 278, 1463, 292, 1260, 578, 579, 681, 740, 833, 1757, 917, 1190, 1225, 1274, 1288, 1682, 1452, 1495, 1610, 1960, 2224, 1609, 1672, 1876, 1684, 1831, 1814, 1940, 1975, 2078, 2464, 43, 132, 1523, 262, 340, 427, 1242, 1320, 2089, 1359, 1420, 1530, 1480, 1539, 1730, 1964, 1732, 1972, 49, 1845, 72, 84, 106, 145, 1670, 167, 272, 332, 425, 513, 567, 1365, 1385, 1756, 1825, 51, 76, 208, 217, 226, 235, 244, 289, 369, 394, 441, 452, 456, 671, 674, 710, 771, 1067, 1232, 1394, 1400, 1433, 1468, 1662, 1761, 1797, 2270, 102, 220, 348, 400, 506, 1256, 627, 666, 1159, 1265, 1398, 1681, 1824, 2345, 2522, 141, 209, 2356, 218, 221, 254, 269, 341, 507, 367, 608, 663, 1424, 713, 714, 736, 1063, 1200, 1496, 1525, 1967, 1992, 1995, 2214, 2443, 2515, 2537, 144, 2315, 232, 1255, 1853, 2061, 2389, 2485, 155, 1201, 210, 325, 1185, 298, 1632, 390, 551, 1717, 605, 626, 1460, 656, 757, 850, 1248, 1380, 1628, 1677, 1767, 1895, 2082, 2116, 2189, 2285, 156, 384, 181, 207, 205, 215, 1701, 404, 1945, 436, 2328, 583, 642, 1343, 1511, 1528, 1622, 1989, 184, 222, 1059, 225, 584, 237, 731, 941, 2579, 227, 532, 818, 1210, 1278, 1338, 1568, 1854, 1959, 2133, 259, 324, 450, 689, 1035, 1160, 704, 735, 1421, 1561, 2010, 260, 281, 301, 407, 1624, 417, 438, 1239, 490, 546, 571, 613, 691, 697, 1301, 1695, 724, 265, 698, 408, 451, 555, 670, 266, 284, 514, 831, 457, 700, 267, 327, 1446, 350, 361, 511, 660, 274, 282, 1129, 524, 2178, 569, 684, 1263, 1793, 2047, 1294, 1405, 1696, 276, 290, 365, 405, 597, 752, 1016, 1044, 1120, 1144, 2001, 277, 381, 445, 1558, 469, 474, 1425, 1788, 283, 326, 349, 529, 685, 1021, 1068, 1573, 1597, 1840, 2295, 294, 1027, 1443, 443, 473, 792, 462, 657, 673, 695, 732, 1054, 1163, 295, 318, 437, 2436, 460, 609, 799, 867, 1026, 1477, 296, 347, 519, 875, 924, 1090, 1150, 1332, 2236, 299, 383, 576, 396, 465, 1399, 539, 635, 688, 944, 1451, 302, 1034, 418, 1519, 494, 591, 1723, 658, 2009, 718, 1501, 1603, 2128, 303, 321, 1694, 336, 536, 2179, 573, 764, 861, 2002, 907, 1296, 1584, 304, 385, 442, 466, 975, 523, 1564, 2253, 305, 1839, 309, 345, 352, 687, 690, 1962, 708, 1212, 946, 310, 331, 415, 433, 694, 809, 1743, 472, 520, 652, 2300, 703, 1336, 313, 359, 444, 515, 1140, 549, 686, 719, 720, 810, 1833, 744, 1105, 1859, 1271, 1493, 316, 1643, 2012, 379, 522, 393, 420, 557, 1813, 596, 722, 1003, 1751, 1081, 319, 1763, 439, 1262, 464, 480, 662, 563, 590, 763, 598, 1585, 320, 334, 356, 377, 1053, 1364, 1648, 1811, 406, 424, 538, 566, 615, 1002, 1118, 322, 629, 364, 531, 967, 430, 516, 1145, 644, 797, 805, 1428, 1498, 339, 1228, 399, 550, 1110, 409, 419, 526, 702, 925, 2145, 1350, 342, 387, 477, 806, 876, 1386, 1629, 2292, 351, 446, 676, 879, 979, 357, 502, 541, 568, 665, 1179, 706, 823, 1007, 1149, 1800, 360, 378, 534, 1131, 2361, 482, 632, 1204, 363, 796, 1143, 429, 500, 512, 556, 791, 622, 636, 840, 2325, 1393, 1601, 1646, 1850, 371, 618, 693, 729, 1169, 374, 410, 486, 509, 659, 560, 715, 1366, 1801, 375, 945, 376, 459, 888, 530, 572, 592, 647, 625, 1123, 730, 1033, 1072, 2004, 391, 1649, 491, 889, 696, 1107, 993, 1316, 1352, 1509, 1464, 2290, 397, 707, 528, 540, 603, 645, 679, 717, 1391, 1489, 414, 432, 449, 475, 593, 966, 680, 692, 1415, 865, 1091, 1526, 2424, 943, 1790, 428, 832, 455, 498, 533, 547, 1373, 1534, 485, 595, 739, 836, 1955, 264, 288, 1607, 2227, 335, 492, 561, 878, 2472, 733, 825, 1578, 1796, 1817, 4, 69, 2430, 2431, 12, 1095, 1892, 1913, 23, 137, 1130, 81, 2231, 98, 129, 954, 99, 1127, 1903, 109, 1126, 2035, 146, 153, 1459, 2216, 2394, 431, 1889, 558, 701, 1323, 1923, 870, 1361, 1020, 1030, 1071, 1093, 1249, 1259, 1299, 1324, 2054, 2055, 1358, 2105, 1363, 1431, 1908, 1877, 1880, 2067, 2381, 1894, 1922, 2327, 1896, 1898, 2026, 2312, 1907, 1988, 2006, 1996, 2555, 2098, 2277, 5, 16, 784, 1315, 39, 41, 1719, 46, 1251, 59, 75, 1809, 96, 677, 128, 1644, 133, 1083, 1371, 1467, 1510, 136, 1024, 151, 1664, 162, 373, 857, 163, 368, 1217, 171, 186, 1605, 228, 389, 231, 1037, 261, 285, 1289, 314, 403, 510, 949, 388, 1066, 1476, 611, 624, 785, 648, 1342, 947, 1000, 1128, 1410, 1490, 1513, 1766, 1540, 1707, 1795, 1810, 2560, 8, 11, 969, 27, 434, 1173, 56, 70, 95, 71, 783, 78, 79, 2411, 89, 113, 93, 111, 191, 147, 174, 183, 211, 353, 423, 525, 675, 2360, 741, 894, 1106, 1383, 9, 189, 42, 90, 198, 1013, 1335, 258, 606, 760, 881, 920, 974, 1178, 1023, 1031, 1154, 1207, 1308, 10, 14, 18, 1481, 60, 586, 2493, 2494, 164, 1141, 216, 1198, 242, 243, 382, 392, 503, 544, 601, 683, 849, 940, 1545, 976, 1177, 2454, 985, 2565, 1086, 1109, 2475, 1112, 1162, 1172, 1174, 1750, 1227, 1432, 1572, 2521, 1665, 1855, 2425, 2562, 2490, 2575, 13, 447, 448, 1389, 15, 24, 859, 1954, 32, 33, 297, 1455, 40, 63, 101, 263, 2352, 120, 612, 122, 150, 134, 306, 158, 1537, 246, 1077, 1148, 247, 772, 287, 330, 333, 358, 1720, 468, 1080, 1406, 559, 1108, 587, 1310, 1529, 1673, 2420, 617, 668, 930, 982, 1011, 1062, 1678, 1065, 1182, 1448, 1470, 1497, 2279, 1508, 2017, 2038, 2333, 25, 1883, 50, 1920, 73, 108, 570, 588, 119, 157, 229, 2144, 565, 721, 599, 871, 1884, 1900, 1911, 2514, 872, 1902, 880, 898, 1948, 1015, 1022, 1886, 1270, 2486, 1881, 1882, 1897, 2147, 2148, 2149, 2382, 1887, 1899, 1901, 1905, 1909, 1917, 1994, 2371, 2492, 2187, 2487, 2274, 2533, 26, 1753, 55, 87, 154, 172, 192, 699, 1862, 107, 892, 114, 1184, 116, 471, 118, 169, 848, 1710, 123, 239, 124, 1435, 1671, 126, 1472, 185, 508, 846, 1006, 2410, 2507, 188, 1686, 1698, 194, 1051, 245, 256, 495, 986, 1253, 545, 1124, 607, 2400, 621, 1096, 628, 643, 758, 1360, 897, 908, 1039, 912, 1285, 923, 987, 1826, 1085, 1254, 1269, 1812, 1307, 1384, 1434, 1867, 1925, 31, 1349, 1928, 54, 2440, 74, 727, 1914, 115, 127, 257, 454, 1679, 280, 300, 411, 497, 1116, 337, 338, 1348, 355, 960, 1543, 2286, 372, 860, 1257, 426, 2217, 440, 619, 1103, 2194, 623, 1827, 742, 756, 813, 2232, 2273, 2275, 2338, 847, 1570, 1608, 1712, 858, 927, 1241, 939, 1276, 1298, 1314, 1356, 1544, 1680, 1885, 2083, 1690, 1754, 1939, 1966, 2237, 1979, 2195, 2211, 2240, 2396, 34, 44, 166, 734, 45, 148, 983, 182, 187, 328, 346, 918, 938, 1099, 1777, 484, 1412, 640, 782, 928, 655, 661, 899, 1524, 937, 1156, 1188, 1413, 1268, 1297, 1300, 1567, 2107, 1311, 1458, 1666, 1714, 2120, 2337, 2347, 2542, 2544, 2546, 2543, 2545, 2549, 2561, 80, 234, 2225, 103, 121, 138, 984, 139, 2302, 2303, 140, 149, 193, 971, 195, 343, 386, 1910, 354, 1347, 470, 637, 2276, 2455, 682, 845, 2157, 856, 981, 1893, 1357, 1469, 1916, 1554, 1615, 1936, 1891, 1904, 1912, 1906, 1968, 2023, 1971, 2034, 2495, 2031, 2063, 2412, 2143, 2452, 88, 159, 117, 2029, 2525, 2554, 125, 1915, 161, 2208, 2505, 489, 493, 580, 631, 795, 781, 1888, 998, 2141, 2578, 1050, 1084, 1205, 1340, 1388, 2008, 1471, 1527, 2370, 2471, 1541, 2570, 1575, 2287, 1918, 1919, 1921, 2007, 2058, 2171, 2190, 2193, 2207, 2294, 2259, 2272, 2379, 2395, 2388, 152, 1171, 2334, 200, 2266, 219, 931, 1606, 250, 2348, 2451, 268, 1492, 2367, 291, 1504, 366, 398, 1327, 416, 1001, 2449, 672, 705, 812, 1331, 1560, 2176, 999, 2238, 1014, 1138, 1175, 1203, 1306, 1195, 1330, 1341, 1454, 1592, 1223, 1596, 2399, 1247, 1252, 1266, 1317, 1322, 1378, 1353, 1367, 1535, 2174, 1441, 1500, 1503, 1637, 1688, 2368, 2177, 2426, 2242, 2318, 271, 602, 1019, 1100, 286, 1978, 2077, 2084, 2039, 2241, 2269, 2556, 2563, 2576, 22, 2101, 255, 1591, 312, 323, 2358, 518, 1049, 604, 929, 614, 616, 716, 1715, 1737, 2221, 630, 1423, 1658, 653, 2466, 669, 808, 1595, 890, 915, 994, 1157, 2013, 973, 1161, 2309, 1293, 1739, 2212, 2468, 2103, 2310, 48, 65, 517, 537, 1520, 1660, 1976, 543, 1816, 553, 594, 1993, 2206, 948, 1782, 961, 962, 2204, 2380, 1043, 1078, 1246, 1659, 1778, 1102, 1155, 1494, 1387, 1409, 2513, 1514, 2264, 1515, 1546, 2081, 1553, 1581, 2256, 1602, 1631, 2491, 1713, 1819, 2056, 2222, 2541, 2252, 2324, 236, 241, 293, 370, 380, 1209, 505, 527, 2418, 779, 1284, 2344, 1287, 1351, 1407, 1444, 2051, 1614, 2448, 1635, 1775, 2439, 2018, 2123, 2196, 2268, 2415, 2534, 307, 2097, 2571, 344, 562, 900, 1482, 2362, 646, 819, 905, 1075, 1442, 1250, 1422, 1565, 1768, 2064, 2359, 2244, 2288, 2271, 2336, 2353, 2459, 2567, 2498, 2564, 308, 855, 910, 1074, 422, 501, 2050, 461, 913, 2506, 463, 1970, 2175, 478, 654, 487, 552, 2234, 581, 773, 600, 633, 1376, 1676, 639, 1594, 774, 956, 957, 1165, 1168, 1630, 1641, 1334, 1502, 2003, 2158, 1586, 1663, 2317, 1598, 2428, 1652, 1755, 1668, 2074, 2092, 2152, 2229, 2473, 315, 1339, 401, 1548, 2445, 421, 499, 1183, 575, 638, 651, 826, 891, 909, 1064, 1167, 1238, 1231, 2032, 1235, 1456, 1237, 2093, 1447, 1506, 1518, 1653, 1762, 1557, 1718, 1823, 1828, 2228, 1977, 2019, 2210, 2024, 2025, 2033, 2573, 2320, 2392, 402, 2386, 412, 542, 620, 650, 798, 828, 1101, 1890, 895, 970, 1018, 1705, 1792, 2053, 2090, 1079, 1114, 1125, 2037, 1137, 1616, 1146, 1261, 1191, 1202, 2437, 1192, 1208, 1716, 1221, 2442, 1473, 1617, 1834, 1837, 2434, 1838, 2354, 1953, 2385, 2021, 2104, 2121, 2127, 2260, 2478, 2185, 2265, 2450, 453, 476, 1010, 481, 483, 1702, 743, 2465, 841, 901, 2280, 2335, 2378, 906, 963, 1215, 1041, 1087, 1104, 1283, 1139, 1186, 1390, 1411, 1700, 1785, 1815, 1947, 1997, 2015, 2146, 2036, 2289, 2419, 2444, 2499, 2559, 488, 2323, 496, 574, 2042, 610, 770, 2205, 786, 1240, 2124, 794, 916, 959, 1028, 1536, 1571, 1036, 1055, 1935, 1136, 1233, 1337, 1291, 1312, 1642, 1318, 1924, 1640, 1820, 1822, 2072, 1848, 2076, 2099, 2186, 2251, 2339, 2476, 535, 548, 582, 775, 1396, 2159, 1789, 2220, 737, 821, 978, 1097, 1875, 1142, 1272, 1805, 2572, 1344, 1392, 1691, 1735, 2307, 1731, 2073, 2102, 738, 2239, 761, 1661, 1806, 2070, 862, 2433, 902, 1746, 989, 1475, 1587, 2446, 745, 815, 868, 2296, 977, 2314, 1164, 1533, 1362, 1484, 2044, 2489, 2508, 1656, 1711, 2166, 2373, 750, 1943, 2346, 934, 952, 1375, 1244, 1709, 1368, 1440, 1846, 1674, 2423, 751, 1538, 942, 1675, 1303, 1325, 1657, 1725, 2199, 2393, 2088, 754, 904, 2470, 788, 1583, 1485, 1627, 1726, 2167, 755, 801, 2219, 843, 1052, 936, 1226, 2548, 1328, 1372, 1507, 1872, 2250, 1419, 1687, 2130, 1612, 1747, 762, 995, 2331, 2409, 829, 887, 1741, 2134, 2365, 767, 935, 2218, 1008, 1060, 1636, 1319, 1516, 1957, 2060, 2085, 2306, 2416, 769, 2366, 2387, 874, 1229, 1277, 1574, 2282, 2477, 1865, 2043, 2233, 2109, 778, 2000, 2022, 814, 2243, 873, 972, 1089, 1395, 1556, 1634, 2112, 2484, 2504, 2569, 790, 1187, 2169, 933, 1047, 1604, 2483, 1176, 2150, 1329, 2071, 1369, 1807, 1397, 2115, 1488, 2245, 1547, 1638, 2230, 1931, 1938, 2108, 2247, 2375, 2577, 2403, 820, 2086, 2122, 853, 911, 1873, 2308, 2372, 2453, 2530, 835, 1005, 1611, 1830, 884, 1295, 1748, 1866, 2369, 2447, 837, 886, 1590, 2432, 919, 1326, 1835, 1181, 1290, 1478, 1965, 2226, 851, 1645, 885, 990, 1152, 1728, 1479, 1932, 2401, 2461, 2552, 852, 991, 2027, 2059, 1098, 1305, 1427, 1655, 1829, 2519, 1849, 2111, 2405, 2281, 2460, 854, 1439, 1569, 1864, 1633, 2183, 2319, 2520, 893, 1046, 2402, 1009, 1313, 2129, 1462, 1961, 2246, 2568, 2463, 2510, 903, 964, 1281, 1521, 1930, 1654, 1736, 2110, 2168, 921, 1784, 2293, 1017, 1153, 1745, 1214, 1304, 1727, 2377, 1381, 1408, 1576, 2391, 1651, 1706, 1740, 1832, 2421, 1990, 2136, 2202, 2341, 2255, 2297, 2404, 955, 1151, 1218, 1417, 1555, 2075, 2462, 1744, 1783, 1804, 1956, 1973, 2135, 2257, 2299, 1004, 1273, 2313, 1512, 1613, 1742, 1856, 2329, 2502, 2535, 1056, 2062, 2566, 1213, 2156, 1282, 2184, 1426, 1474, 2503, 1189, 1224, 2422, 1264, 1370, 1982, 2553, 1522, 1418, 1559, 1689, 1697, 2408, 1752, 1760, 2142, 2151, 2209, 2263, 2298, 2516, 746, 842, 1243, 1517, 1566, 2321, 1781, 1934, 2479, 747, 1487, 1379, 2170, 2355, 2407, 748, 1857, 1180, 1562, 2118, 2201, 1749, 1794, 2114, 1808, 1868, 2137, 749, 822, 882, 1626, 1969, 2125, 2529, 765, 1933, 1222, 1499, 2162, 2482, 766, 834, 992, 1280, 1429, 1699, 2469, 2164, 2326, 2417, 780, 1621, 1786, 2262, 1937, 2501, 787, 1117, 1847, 1841, 2181, 789, 1404, 2441, 804, 1073, 1986, 2068, 2163, 2322, 2079, 2192, 811, 2342, 932, 1549, 2364, 2528, 1170, 2429, 2020, 2065, 2100, 2311, 816, 1038, 2350, 1245, 1650, 1791, 2132, 2182, 824, 1236, 866, 922, 1577, 2016, 1045, 1058, 1122, 1600, 1950, 1987, 2138, 2165, 2249, 830, 2284, 951, 1211, 2349, 1593, 2046, 2198, 2527, 838, 896, 1199, 1465, 2488, 863, 1111, 2511, 1589, 2126, 1724, 1871, 1984, 2014, 2045, 2363, 2457, 864, 1070, 1082, 2080, 1121, 1776, 2131, 869, 980, 1620, 2069, 1115, 1193, 2041, 2188, 1345, 1416, 1491, 1708, 2119, 2316, 1836, 2215, 2509, 926, 2456, 1032, 1951, 1983, 2197, 950, 1302, 1486, 1550, 1639, 2096, 2117, 2340, 2305, 2540, 953, 1843, 2261, 1863, 2040, 2155, 2414, 1012, 1267, 1704, 1870, 2474, 1025, 1401, 1445, 1703, 1779, 2557, 1048, 1844, 2154, 2200, 1453, 2258, 1722, 1759, 2512, 1861, 1998, 2091, 2330, 2384, 2413, 2547, 2438, 1061, 1135, 2539, 1625, 2357, 2496, 1076, 1354, 2254, 2458, 1134, 1194, 2343, 1147, 1842, 1869, 1158, 1551, 1693, 2398, 1166, 2390, 1991, 2427, 2481, 2500, 1216, 1780, 1999, 2172, 2397, 1230, 1623, 2283, 2480, 1333, 2574, 1450, 1466, 2048, 2191, 1377, 1963, 1403, 1449, 1941, 2113, 2173, 2467, 1430, 2180, 2531, 2558, 768, 827, 1974, 1985, 776, 1879, 807, 883, 1094, 1346, 1436, 1542, 2351, 1764, 1851, 2139, 2406, 2523, 777, 1878, 914, 1438, 1799, 2028, 2052, 2203, 996, 1196, 1355, 1683, 1774, 800, 1234, 1729, 1942, 2030, 2332, 2140, 2532, 803, 817, 1457, 1040, 1929, 1552, 2161, 2374, 1765, 1852, 1980, 2223, 2536, 988, 2524, 1029, 2005, 1770, 2235, 1667, 1758, 2518, 2435, 1769, 1773, 2160, 2517, 1771, 2213, 1798, 2087, 2526, 2094, 844]
2580

In [1]:
import pandas as pd

In [3]:
orderData = pd.read_csv('dataMyself/订单信息.csv', encoding='GBK')

In [6]:
areaID_list = orderData['病区ID'].unique().tolist()
areaID_list = [item[1] for item in sorted(enumerate(areaID_list), key=lambda x:x[1])]

In [8]:
areaName_list, hospital_list = [], []

for areaID in areaID_list:
    [areaName, hospital] = orderData[orderData['病区ID'] == areaID].iloc[0][['病区名称', '医院名称']]
    areaName_list.append(areaName)
    hospital_list.append(hospital)

areaData = pd.DataFrame({
    '病区ID': areaID_list,
    '病区名称': areaName_list,
    '所属医院': hospital_list
})

In [9]:
areaData

    病区ID        病区名称 所属医院
0     34     1号楼 13楼   WT
1     38     1号楼 17楼   WT
2     40     1号楼 19楼   WT
3     43      1号楼 3楼   WT
4     44      1号楼 7楼   WT
..   ...         ...  ...
58   374   2号楼 1楼 急诊   YH
59   375      2号楼 2楼   FQ
60   810      2号楼 1楼   FQ
61   824  7号楼 10楼 肾病   FQ
62   833   8号楼 6楼 产科   FQ

[63 rows x 3 columns]

In [10]:
areaData.to_csv('病区数据.csv', index=False)

In [1]:
import pandas as pd
import json

In [29]:
data = pd.read_csv('dataMyself/订单信息.csv', encoding='GBK')
data

,订单号,费用,已支付费用,已退款费用,服务天数,医院ID,医院名称,病区ID,病区名称,床位号,...,服务商名称,患者年龄,患者性别,护工ID,护工姓名,订单类型,接单时间,关闭时间,创建时间,科室
0,3.800000e+16,960,0,0,4,3,YH,278,2号楼 14楼,29,...,JSMSJ,55,男,1662,赵桂琴,一对一,未知,2023/12/12 17:52,2023/9/2 9:45,未知
1,3.800000e+16,720,0,0,3,3,YH,277,2号楼 13楼,23,...,JSMSJ,53,男,1673,杨莉,一对一,未知,2023/12/12 17:52,2023/9/2 10:03,未知
2,3.800000e+16,1440,0,0,6,3,YH,276,2号楼 12楼,54,...,JSMSJ,52,男,1651,杨宏霞,一对一,未知,2023/12/12 17:52,2023/9/2 10:32,未知
3,3.800000e+16,1250,0,0,5,3,YH,288,3号楼 2楼 心内三,48,...,JSMSJ,73,女,1686,董亚红,一对一,未知,2023/12/12 17:52,2023/9/2 11:05,心内三
4,3.800000e+16,200,0,0,1,16,FQ,369,6号楼 4楼,42,...,JSMSJ,78,男,1507,吴和芳,一对一,未知,2023/12/12 17:52,2023/9/2 11:17,未知
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,1.790000e+17,500,500,0,2,16,FQ,353,7号楼 5楼,38,...,SHZF,74,男,6214,杨峰,一对一,2024/9/26 7:53,未知,2024/9/26 7:52,未知
2576,1.790000e+17,900,900,0,3,16,FQ,833,8号楼 6楼 产科,18,...,SHZF,33,女,5491,胡彦春,一对一,2024/9/26 9:21,未知,2024/9/26 9:21,产科
2577,1.790000e+17,600,600,0,2,2,WT,44,1号楼 7楼,未知,...,NBAX,32,女,4927,闫桂妮,一对一,2024/9/26 12:56,未知,2024/9/26 12:56,未知
2578,1.790000e+17,500,500,0,2,16,FQ,371,6号楼 6楼,1,...,SHZF,62,男,6332,贺昔妹,一对一,2024/9/26 16:48,未知,2024/9/26 16:40,未知
2579,1.790000e+17,1250,0,0,5,3,YH,306,5号楼 9楼,32,...,JSMSJ,67,男,1599,黄玉枝,一对一,2024/9/26 19:52,未知,2024/9/26 19:39,未知

In [30]:
def transformOrderID(orderID, createTime):
    [date, time] = createTime.split(' ')
    [year, month, day] = date.split('/')
    [hour, minute] = time.split(':')
    month = '0' + month if len(month) == 1 else month
    day = '0' + day if len(day) == 1 else day
    hour = '0' + hour if len(hour) == 1 else hour

    return "{:.0f}".format(orderID)[0:5] + year + month + day + hour + minute

In [31]:
data_json = {}
for _, row in data.iterrows():
    ID = transformOrderID(row['订单号'], row['创建时间'])
    data_json[ID] = {}
    for col in data.columns[1:]:
        data_json[ID][col] = row[col]

In [32]:
with open('order.json', 'w', encoding='utf-8') as file:
    file.write(json.dumps(data_json, indent=4, ensure_ascii=False))

In [3]:
nurseData = pd.read_csv('dataMyself/护工信息_已脱敏.csv', encoding='GBK')

import random
indices = random.choices(range(0, 574), k=10)
indices

[144, 242, 237, 154, 10, 324, 118, 563, 210, 370]

In [5]:
for idx in indices:
    print(nurseData.iloc[idx][['护工ID', '护工姓名', '主要负责病区']])

护工ID      1686
护工姓名       董亚红
主要负责病区     3号楼
Name: 144, dtype: object
护工ID      2704
护工姓名       项菊秋
主要负责病区     5号楼
Name: 242, dtype: object
护工ID      2697
护工姓名       符秀翠
主要负责病区     3号楼
Name: 237, dtype: object
护工ID      1697
护工姓名       黄梅菊
主要负责病区     3号楼
Name: 154, dtype: object
护工ID      1503
护工姓名       葛玉翠
主要负责病区     7号楼
Name: 10, dtype: object
护工ID      4806
护工姓名       高雪玲
主要负责病区     1号楼
Name: 324, dtype: object
护工ID      1654
护工姓名       陈玉妃
主要负责病区     5号楼
Name: 118, dtype: object
护工ID      6238
护工姓名       袁晓红
主要负责病区     6号楼
Name: 563, dtype: object
护工ID      2031
护工姓名        丁俊
主要负责病区     3号楼
Name: 210, dtype: object
护工ID      4946
护工姓名       史玉燕
主要负责病区     1号楼
Name: 370, dtype: object